from datetime import datetime
from pydantic import BaseModel, ConfigDict


class RoleBase(BaseModel):
    name: str
    description: str = ""


class RoleCreate(RoleBase):
    pass


class RoleUpdate(RoleBase):
    pass


class RoleRead(RoleBase):
    model_config = ConfigDict(from_attributes=True)

    id: int
    company_id: int
    created_at: datetime
    updated_at: datetime


class UserCreate(BaseModel):
    """Used when provisioning a new user. Firebase UID is generated by Firebase."""
    email: str
    name: str = ""
    role_id: int
    is_active: bool = True
    password: str  # initial password set by admin; min 6 chars enforced by Firebase


class UserUpdate(BaseModel):
    """Used when updating an existing user record."""
    firebase_uid: str
    email: str
    name: str = ""
    role_id: int
    is_active: bool = True


class UserRead(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: int
    firebase_uid: str
    email: str
    name: str
    role_id: int
    is_active: bool
    company_id: int
    created_at: datetime
    updated_at: datetime


class UserMeRead(BaseModel):
    id: int
    email: str
    name: str
    role_id: int
    role_name: str
